sudo: required

language: ruby

services:
  - docker

os:
  - linux

rvm:
  - 2.4.2
  - 2.4.1
  - 2.3.1
  - 2.1.5

before_install:
  - cd docker && docker build -t processor-rabbitmq .
  - docker run -d -p 5672:5672 -p 15672:15672 --name processor-rabbitmq processor-rabbitmq
  - cd ..
  - gem install bundler --version '~> 1.16.0'
