version: '3.3'

services:
  rabbitmq:
    build: .
    container_name: eventhub.rabbitmq
    image: eventhub.rabbitmq:3.8.14
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"
