name: ci

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

  schedule:
  - cron: 0 2 * * 3,6

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.4', '3.3', '3.2']

    name: Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: latest
        bundler-cache: true
        cache-version: 4

    - name: Setup RabbitMQ
      run: |
        cd docker && docker build -t processor-rabbitmq .
        docker run -d -p 5672:5672 -p 15672:15672 --name processor-rabbitmq processor-rabbitmq

    - name: Run default task
      run: |
        bundle exec rake
